package io.lucamoser;

import jota.utils.Converter;

import java.util.Random;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicInteger;

public class Main {

    private final static int HASHERS_COUNT = 4;
    private final static int HASH_LENGTH_TRITS = 243;
    private final static int NUMBER_OF_ROUNDS = 81;

    private static AtomicInteger count = new AtomicInteger();

    public static void main(String[] args) throws InterruptedException {
        String[] txsTrytes = {
                "SDUXIDXTLYYMYIJFYSFTCVDPGBONBRBMNONKLQNO9ZFNFHVDDTDYTS9TR9UNPRCVRTRPXXUBSXMBI9RZUGXVRIHH9UFFNQQTGWGW9FTCQUZGLXAARYBEVDGJ9HWENQRFKAUBJDWIIAMKRNKSXKFXSDQPEFJOPANSWQGNWIZEQPWHIJDAQSMMHHMVSAYCLJDNZFNMRIPAJLODMZHEPFEDTCOMMSKZKYCBPC9QJWROCDBYSBOJLHBRGAHSUVSFDWMKZWUSPLOXUJSDTFQMMLUVGX9LTRYGSA9JIFINNZBDSYDFKBZ9XHFQNREACFQOZPNRHTZCYTZFY9WXYKFRSVCUGJMIV9NESRNQEINRXX9BGHFINWCIAMAYGZ9KYKLHYYNW9GZ9MVSIQGTWDRKJZEUO9HFJZMJMFPIDJ9VWPTCQOJ9WCVYRAHKOKDJUCMMGDVOABL9FUETQGPWOFPIHTLMQHUQSUIHWYZHEVGFPJMXATGLNFBOTYEFCDGS9VWQEGSDLI9EDDKFUZBEELQCUFTCOWWLTGSCBRYBXIGSOOBCLUPZ9E9EFIQLQVCTIGGBNHSULZTBJVOVNQTLESQKQJFEJRKQFWOHRWHNDGJWEFFC9WBQOSSJYPH99FZPRKBJQVPNOYXSLWFDHEPWVABDVDGAQXBQULQWFQHKSNCEHPYHJZEXISWMD9OYWND9AFFYXQ9VIMTCQHIEOOATRCE99TRUWCYJFIFYLINEUZNQQEKXQCQ9FNXPVOXAJIXTUIXENPGJXNUNTHLLTZDSEFNTDZ9MGVGIRXMFEXSHLFMZXZKSY9VSWAGSPHRSQYSVESPJUKHMCZVMMQO9JHYWWFKLARCSANKXTWTUAQXTXYXCEUVLQUYXQDWHH9JECMLCFMXLTMO9YMBJFAXIWI9AFOZDFFVBTUOEERCSWCNKRIHZW9BBQKMWHQQNVLEPTESSTHKQNGABQAZVZSJRVSBMOGWTHFDHGX9BAWBIFAUKTOGWOODLXHNRRILDUDYMMHHLNBJSLYZ9VDGPSYHBVVFMNJDERXCHSAYAKQLPVCDTTYIUVPYSORDCAUXSTWBNBYDVJMDLQSSPGKGMXYR9VXJVWPRGHWQOSXKRTIZMBWYELKVB9JPANZVEZUCITUIWPEOWLIGWLEAFDBSMCXBWOB9WCSTPIMQRYNUQKWJUL9TUUBEMQWULUFSMRDMZBWFAUHBHPPWLFDJ9Q9XVYZGWFSACMCXTBGZSTGRFYGZZDYBVAXZRJEEAQBXKXEAYNUZZPHUPUPWGGGJQDTMKNVFNUTBAAGSUJORUUUAJWLJXECKRDKJDTCZRCZXKWAOMYHEBLPZFMDCDBXMQTAJHM9QWODFCLX9BCXDRTNPRUWFIII9OICRGLYRFELHHBCGTUGTSKWHPRTCRHNASRXAKBIOPPTVYBAPHOFSMBAUEWHJNDOQA9MOJVFILPQJMVHPNSHEGLIPYUMNYGHAWATSIJWOGVHIGOSBAWDBWJKIYYVADJGGCIOBVQBWAWDSMTMXWBLVGLCGYPDBXIISO9DGXNMYRAVPWNEKCTBJDCBSLMMLWAQFOVETRACGUJZXTSHYYBZOIBYHUAMTENTEHCBAUNUSZMOIJGL9FPBFMPKDTCUHVRIHCVZMTIJP9MHJJTDSCGYMQSYHEMVBZOFHENDJMCJSHEHBCHALPQZGRWBAUYKFUARXBK9UBETMC9XEFNJSFQAEHOKCBCSBCPZTUHMGDQNOQNVRWV9OYYLWXJA9UJPZCKZSQRRJNCMZZWQQCWT9IICTLRSBUIUHOK9BSUR9ZN9CQHEBTWWWQUHRCYFUFFVHUC9JPXSVUZKYGBXPMUUEBYFGYTWNSSUXKBTXEJV9Q9WBJSXFHIFIKE9FXXQZTTBYQW9MTKJI9IJZPVJMHMV9TPYKXETVWHKFXVB9JQZPRZMLNB99YJA9HSTAIAVVTYDCDMKNBDYAYUKQIO999HTAGYGBVAXWPNNN9IRBKKQSIQDEFIMB9IZVOV9CIOFBKIGNHFSFOPXPQZZXIGOFHPNPTDQSYJZGRA9SKDQFPVJPBEXF9KMNNTPXQAEMWUFAZKPRMFHEQFXITLUH9ONUNM9YYQGWOGMCADAXJWWOBZQPKDFWAFWXLWQZPYAWRNSSUXGUTSPFAOJD9KWCPMGLOPKHCGJQKY9UPXWWFVYIENWXJGDSFZCOIIKTWYYDKBTVA9VHSWUNEH9OXDUYPM9NAOZJQUFGBLCSGMCDLMMBHCQSWMRNJETYOOEM9IBEMATEG9RHEQ999999999999999999999999999999999999999999999999999999UOKJC9D99A99999999C99999999DEQGXGYJCFIRJH9JPJJIFJBFRHETSQKGQHIKHKYJWBLXIBGAEIFYOTPUALUW9LLEEKJLIKWESCNHUQBQWIXWKHIZ9QMYHCTNMXIIBDDXSIAPWJLPAEHZLRBVLPRMQOPRNVQPCWQVLYQUQCQLWCDKVXTXSMI9J99999B9YRBSYFOCOUCSISYY9ALQRLJWLC9NMVXTEZ99CRWQCVHLDLZNTQROHFMLRBYHKFHISZFAIUTZVC99999999999999999999999999999999ZB9XJQIME999999999MMMMMMMMMWTJYONNCOQXXBJZMMXXN9PHNHEL",
                "YMVWJM9QZJQAHMUNAUAXERLVTKECFHLWP9EQOZTHVB9QURCEBJRGSHZMWNGXMIBGTSUPUBXQGYJPOELQZBOYSRCJHARQTKTIFXRPEPJGFPKLDIFZCQJDCPKGTWXBNMIYSUSOJEKTTSV9XRIHVMJD9SEHQCNWUICDAXEPJKUKAEMBZYIEUHNU9KGHNCSGIKAOLUZG9YDGUZZ9MWY9FXAHVDTIUUMTKTBGJBVJWKLKZL9SVDEPROWZTQCTPP9PAZZQIECMJHIV9ZIWXNFAJJWZKKBSCGCYGDRZNOVQSQHGWEYLWXPOEME9DSXECGOCIUKCPDXDZKDRFXC9HDHEDUU9FCROXERPL9BRMJRMPAJ9WAQFHPTFVQFLPORTKZOYP9TUE9LHWBUEIVXLITENAJVJWGGKN9GVZWWLCLKECLB9PRGPPUIDSDLLGTULFOLHZVJENXUKJCOPFQEQJCNRHYFQELBEO9YPDIOTZCYVACF9WKQWW9UUTRBSOSNUMU9OJUDGYACVJUPAEV9UFIWWDEIXFGBQNZLNBE9LXM9UUDMHYALFVMAGCONJBKDGNALI9CITSGXMJRBWCZEPLXZYSMAMYUSTWNIAQMKIOVIEJQTALOLSWRJYOBDKBDABZMJPXAQDTGSCJYXXCXODMDTFSDJKROCFAMROHFOPFBFQFEOTABDKHIABKXGR9EKVKSCSFLZQAEXOYOFVSSHXLRE9B9SMCW9LWDPERFAUZRYEGQFCSJWMGVKBHLRLDYHY9TTAGXH9IH99CYCQYUQJNPGFXVD9CBSPNDIDTPLB9O9GIGPJWASAQPMENICSBYR9KHFSKR9RUSQUDUZZOQCAHBVKDJZPRFZ9WIBQWRSLBDK9QUTZAARRLJXL99EOAPXTSTXDGGTWUFDIOKURNPE9Z9KNLHLIUOL9CEUKJCRAMSFNMQUBQHRLUNQRZJNILHRPTXCOG99JOR9EYZMOUHQCNYCJNXD9OHLWKAUQSKFCBF9BZSXRQ9UZVUIKXMGR9FUGNLKXVWIPH9QPQLDNVDEWWCCKZWNWGJPQNCIGYZXWAIL9GSJXJMZFSIM9SCHREQDUUK9RUCMLJIHOI9NAYXPNIWHZIPAFSOVEOKVCWTSKLGUSBORCQUPKTDIXTVCAUXUMYJBYFZPEBBG9NYYWAMWNWEXEP9BSSOKEIUTHFQEJGITHOCSBJCCWAIYVEGT9ZZUGAVYDQT9TNZFOYYLVNYXQESLGFQDLYPAYNNDNECWYU9DGZNEADGSZJBUJABITBYHVDTKXAFGIIBQXZZXPIKQGQDCXGLDROLKSKATALIHH9WSXVYUGCYMMKUHFYMNXYHDK9D9DUZWEFYWKGJLO9MRUCSOBQMETWVOCSNGBEXBZCPTNJJONPYEYSXBJYTFHMGHFPUCJMWSPIRZZHHVSCUPNRBFDVG9ASNF9MPIZJUINEUQEMIEQKYUODCUZPYEBERWVWXRSUXTVNQOSYWKRKJJUVYTUUJHDKFLTHHIO9DMHZWWGCNBO9HSZOHQC9NYRZEXRHNU9VNNGBXXIPTGINTIESYZ9LBVASHSRTKMNMHWYNXNKRP9FYJRAKFCXYKWNVMOLWWUNRLHTYZDE9PNOVSRMEFLSEYNA9CGEHB9IKTIOWMLOIJAKXKNFKLO9KDQDDNSLKLDWOMIKNIGIURTAIIKGKOAHUFSOBMAZBV9LPELCXYH9XUGVBBYYUMJUXCXKO9DIXRLJPEUQXHMTFCSDZIJGZBOJSDPVIYPWO99DBLIVUKUWWOYCSVADULYPYEEGTBVCX9YCIUFCDYQVGPINNNWVECKACRLZPEJJCYSTIDNDINVGYKBBPJLRK99KOFGDJXAKKMZLRPNRYCSDSJZMBOBNXVCJSOWYERFEHLD9XJIOXAUATNFVPHEVETEXRNHHWRTVA9K9ZUXSXRMJ9BEBNMZL9IYOCCY9D9JBIXGZDEALHCMNVPMERGLMJPUSJIDPGQXSUQKDXAWRTCZZXJCBRFWLLZJFNJBYOJ9AUDCUXCTV9KWPYGBMAYODVHPVZVWGALVKAYVVPHJISPJOEPIYFWAOUWHVNZGFNRPDFDTRVYRCEVZGTNSFYKJILMEWVGNPBMPEDDJCKHFGONPTIT9TGPUPU9QFOTHYLDUFSOROXZDGD9XRUS9FYAHMNZXMXOUMFPQGXWAKORUPOIIDCSWHHBXLZBVRACKBQFXSE9RMTXBOJODIUSUDIL9QCAYOTWHZZYP9DLLDVJHEUWZTAWIAPCZPWQCQBDESJ9VAULUC999999999999999999999999999999999999999999999999999999QRKJC9D99B99999999B99999999WMBMHZNKFZFIAFGSIKRLU9R9XCIENFMXKAETU99AQVGIAEVKSJLZWCKAJ9AJDINUHNCWBZCNHYGSYDBFCQXAWVYHEHPRTQ9RBEVHHQXMAWPQYHDC99OYHZZBXVFGPHNIOBYFLOMZUPFEWUNNHOTLNIGSXMKTLZ9999QXAWVYHEHPRTQ9RBEVHHQXMAWPQYHDC99OYHZZBXVFGPHNIOBYFLOMZUPFEWUNNHOTLNIGSXMKTLZ9999999999999999999999999999999NZS9JQIME999999999K99999999POWSRVIO9999999FGGENGKTNNNP",
        };

        // conversion from tryte strings to ints (iota-java returns an int array) to bytes
        int[][] txTritsInt = new int[txsTrytes.length][];
        for (int i = 0; i < txsTrytes.length; i++) {
            txTritsInt[i] = Converter.trits(txsTrytes[i]);
        }
        byte[][] txTritsBytes = new byte[txsTrytes.length][];
        for (int i = 0; i < txTritsInt.length; i++) {
            txTritsBytes[i] = new byte[txTritsInt[0].length];
            for (int j = 0; j < txTritsInt[0].length; j++) {
                txTritsBytes[i][j] = (byte) txTritsInt[i][j];
            }
        }

        if (args.length > 0) {
            runSlowCurl(txTritsBytes);
            return;
        }
        runBatchedBCTCurl(txTritsBytes);

    }

    public static void printHash(byte[] trits) {
        int[] intArray = new int[trits.length];
        for (int i = 0; i < trits.length; i++) {
            intArray[i] = (int) trits[i];
        }
        System.out.println(Converter.trytes(intArray));
    }

    public static void printHashesPerSecond() throws InterruptedException {
        int last = 0;
        for (; ; ) {
            Thread.sleep(TimeUnit.SECONDS.toMillis(1));
            int hashed = count.get();
            System.out.printf("hashed %d (%d/s)\r", hashed, hashed - last);
            last = hashed;
        }
    }

    public static void runBatchedBCTCurl(byte[][] txTrits) throws InterruptedException {
        BatchHasher[] hashers = new BatchHasher[HASHERS_COUNT];
        for (int i = 0; i < HASHERS_COUNT; i++) {
            hashers[i] = new BatchHasher(HASH_LENGTH_TRITS, NUMBER_OF_ROUNDS);
        }

        ExecutorService feedThreadsPool = Executors.newFixedThreadPool(HASHERS_COUNT);
        for (int i = 0; i < HASHERS_COUNT; i++) {
            final int id = i;
            feedThreadsPool.submit(() -> {
                try {
                    Random random = new Random();
                    for (; ; ) {
                        HashReq req = new HashReq();
                        req.input = txTrits[random.nextInt(txTrits.length)];
                        req.callback = trits -> {
                            count.incrementAndGet();
                        };
                        hashers[id].hash(req);
                    }
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            });
        }

        ExecutorService hashersPool = Executors.newFixedThreadPool(HASHERS_COUNT);
        for (int i = 0; i < HASHERS_COUNT; i++) {
            final int id = i;
            hashersPool.submit(() -> {
                try {
                    hashers[id].runDispatcher();
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            });
        }

        printHashesPerSecond();
    }

    public static void runSlowCurl(byte[][] txTrits) throws InterruptedException {
        byte[] hashTrits = new byte[Curl.HASH_LENGTH];
        Thread curlThread = new Thread(() -> {
            Random random = new Random();
            for (; ; ) {
                Curl curl = new Curl();
                curl.absorb(txTrits[random.nextInt() % txTrits.length], 0, txTrits.length);
                curl.squeeze(hashTrits, 0, Curl.HASH_LENGTH);
                count.incrementAndGet();
            }
        });
        curlThread.start();

        printHashesPerSecond();
    }
}
